server:
  port: ${server.port}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: ${database.jdbc.url}
    username: ${database.username}
    password: ${database.password}

resource:
  thymeleaf:
    prefix: classpath:/templates/
    #prefix: file:src/main/resources/templates/
    cache: false

logging:
  level:
    root: DEBUG
    org.springframework.boot: ERROR