server:
  port: ${server.port}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: ${database.jdbc.url}
    username: ${database.username}
    password: ${database.password}

resource:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false