spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mysql
    username: root
    passsword: 1234

resource:
  thymeleaf:
    prefix: classpath:/templates/
    #prefix: file:src/main/resources/templates/
    cache: false
